import type { Metadata } from "next";
import PageShell from "@/app/_components/PageShell";
import Shot from "@/app/_components/Shot";
import { alternatesFor } from "@/app/_lib/site";

export const metadata: Metadata = {
  title: "Coaching from your Apple Health running history",
  description:
    "RunToMax reads the runs already in Apple Health, estimates a threshold pace from your last 90 days, and gives every run a plain-language verdict. What is computed on device, and what the optional cloud coaching adds.",
  alternates: alternatesFor("/features/coaching-from-apple-health/", "en"),
};

export default function CoachingFeaturePage() {
  return (
    <PageShell
      lang="en"
      eyebrow="Feature · Coaching"
      title="Coaching from the runs you already have"
      alternate="/fr/fonctionnalites/coaching-apple-sante/"
      updated="2026-09-22"
      intro={
        <p>
          On first launch, with your permission, RunToMax reads the runs already in Apple Health and builds a starting profile from them.
          Your history counts from day one; the coach does not start from zero.
        </p>
      }
    >
      <h2>The starting profile</h2>
      <p>
        From your recent runs RunToMax estimates a <strong>threshold pace</strong> — the pace you can hold for roughly an hour — using the
        last 90 days of running. Training paces (easy, marathon, threshold, interval) are derived from that anchor. When there is not enough
        recent running to support an estimate, the app says so rather than inventing one, and the estimate is refined as you record runs with the Watch.
      </p>
      <Shot src="iphone-today.png" alt="RunToMax Today screen on iPhone with the day’s guidance" caption="Today: one answer before the run." />

      <h2>A verdict after every run</h2>
      <p>
        RunToMax waits for the run to be finalized in Apple Health, then classifies what kind of run it was — easy, long, tempo, intervals,
        race — and writes a short verdict: what the run tells you, and what to do next. The findings are aware of the run type and your heart
        rate, so a cool-down does not read as a fade and a hot day does not read as lost fitness.
      </p>
      <Shot src="iphone-training-impact.jpg" alt="Training impact screen showing aerobic and anaerobic stimulus for a run" caption="Training impact, grounded in the finalized run." />

      <h2>Every plan day gets a score</h2>
      <p>
        When you follow a plan, each session is scored against what was asked: pace, duration, structure. The score is the unit of comparison
        across the plan, so “how did this week go” has a number behind it and the number has an explanation behind it.
      </p>
      <Shot src="iphone-metric-explainer.jpg" alt="Metric explanation screen: what a number is, why it changed, what to do next" caption="Every important number explains itself." />

      <h2>Readiness and heat</h2>
      <ul>
        <li><strong>Readiness</strong> combines heart-rate variability, sleep and recent training load from Apple Health into one read for the day.</li>
        <li><strong>Heat-adjusted targets:</strong> pace targets are adjusted for temperature and humidity at your location using Apple Weather, so a target set in April is not enforced in July.</li>
      </ul>

      <h2>What runs on the device, and what does not</h2>
      <p>
        Everything above — the profile, threshold and training paces, run classification, the verdict, plan scores, readiness and heat
        adjustment — is computed <strong>on your iPhone</strong>, with no account and no RunToMax server involved.
      </p>
      <p>
        The one optional cloud feature is the <strong>written coach notes</strong>: longer explanations generated by a language model through a
        RunToMax proxy. It is off until you turn it on, it receives a minimized summary rather than your raw data, and turning it off removes
        nothing else. With cloud coaching disabled, the app is complete; the notes are simply shorter.
      </p>

      <h2>Where your data lives</h2>
      <p>
        Your runs, routes and heart rate live in Apple Health on your device. RunToMax keeps no cloud copy of your training history and has no
        email/password account. Runs can be exported as FIT files. Details are in the <a href="/privacy/">privacy policy</a>.
      </p>
    </PageShell>
  );
}
